{-# OPTIONS --safe --without-K #-}
-- SPDX-FileCopyrightText: © 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
-- SPDX-License-Identifier: MPL-2.0
--
-- Theorem B, Target 4 — Honest Generation (HC-*) and Veridicality (L*),
-- ported from Trope/Generation.idr and Trope/Veridicality.idr, AND connected to
-- the calculus: the writable effect atoms are honest, and honesty is closed
-- under ▷, so a well-formed term NEVER produces a deceptive grade (HC-3 / the
-- prevent-variant: the dangerous deceptive states are unreachable by construction).
--
-- This target is reached because Targets 1–3 landed. The algebra facts port as
-- pure finite case analyses; the calculus metatheorem (honesty closed under the
-- non-commutative ▷) is the new content, and it is sorry-free.

module TB.Honest where

open import Data.Bool.Base using (Bool; true; false)
open import Data.Product.Base using (_×_; _,_; Σ; ∃)
open import Relation.Binary.PropositionalEquality using (_≡_; _≢_; refl)
open import Relation.Nullary using (¬_)

open import TB.Grade
open import TB.Syntax using (atten-atom; drop-atom; sever-atom; predicate-atom)

--------------------------------------------------------------------------------
-- Veridicality (Veridicality.idr): the THREE deceptive duals, one per coordinate.
--------------------------------------------------------------------------------

isDeceptiveFate : Fate → Bool
isDeceptiveFate falsified = true
isDeceptiveFate _         = false

isDeceptiveBond : Bond → Bool
isDeceptiveBond misbound = true
isDeceptiveBond _        = false

isDeceptiveMerge : Merge → Bool
isDeceptiveMerge conflated = true
isDeceptiveMerge _         = false

-- Uniqueness: each coordinate's deceptive predicate holds for exactly one value.
fateDeceptiveUnique : ∀ f → isDeceptiveFate f ≡ true → f ≡ falsified
fateDeceptiveUnique falsified _ = refl

bondDeceptiveUnique : ∀ b → isDeceptiveBond b ≡ true → b ≡ misbound
bondDeceptiveUnique misbound _ = refl

mergeDeceptiveUnique : ∀ m → isDeceptiveMerge m ≡ true → m ≡ conflated
mergeDeceptiveUnique conflated _ = refl

-- The catalogue of the three deceptive duals (calculus: "exactly three").
deceptiveDuals : Fate × Bond × Merge
deceptiveDuals = falsified , misbound , conflated

--------------------------------------------------------------------------------
-- Generation (Generation.idr): the five atomic moves generate the HONEST values.
--------------------------------------------------------------------------------

data Move : Set where
  Preserve  : Move
  Attenuate : Δ → Move
  Predicate : Move
  Drop      : Move
  Sever     : Move
  Fuse      : Move

moveFate : Move → Fate
moveFate Preserve      = present
moveFate (Attenuate d) = atten d
moveFate Predicate     = predicated
moveFate Drop          = dropped
moveFate Sever         = present
moveFate Fuse          = present

moveBond : Move → Bond
moveBond Sever = severed
moveBond Drop  = withheld
moveBond _     = intact

moveMerge : Move → Merge
moveMerge Fuse = fused
moveMerge _    = single

-- (1) The atoms produce only HONEST values (never a deceptive dual).
movesHonestFate : ∀ m → isDeceptiveFate (moveFate m) ≡ false
movesHonestFate Preserve      = refl
movesHonestFate (Attenuate d) = refl
movesHonestFate Predicate     = refl
movesHonestFate Drop          = refl
movesHonestFate Sever         = refl
movesHonestFate Fuse          = refl

movesHonestBond : ∀ m → isDeceptiveBond (moveBond m) ≡ false
movesHonestBond Preserve      = refl
movesHonestBond (Attenuate d) = refl
movesHonestBond Predicate     = refl
movesHonestBond Drop          = refl
movesHonestBond Sever         = refl
movesHonestBond Fuse          = refl

movesHonestMerge : ∀ m → isDeceptiveMerge (moveMerge m) ≡ false
movesHonestMerge Preserve      = refl
movesHonestMerge (Attenuate d) = refl
movesHonestMerge Predicate     = refl
movesHonestMerge Drop          = refl
movesHonestMerge Sever         = refl
movesHonestMerge Fuse          = refl

-- (2) Every HONEST value is generated by some move (coverage).
genFate : ∀ f → ¬ (f ≡ falsified) → ∃ λ m → moveFate m ≡ f
genFate present    _   = Preserve     , refl
genFate (atten d)  _   = Attenuate d  , refl
genFate predicated _   = Predicate    , refl
genFate dropped    _   = Drop         , refl
genFate falsified  neq = ⊥-elim (neq refl)
  where open import Data.Empty using (⊥-elim)

genBond : ∀ b → ¬ (b ≡ misbound) → ∃ λ m → moveBond m ≡ b
genBond intact   _   = Preserve , refl
genBond withheld _   = Drop     , refl
genBond severed  _   = Sever    , refl
genBond misbound neq = ⊥-elim (neq refl)
  where open import Data.Empty using (⊥-elim)

genMerge : ∀ m → ¬ (m ≡ conflated) → ∃ λ mv → moveMerge mv ≡ m
genMerge single    _   = Preserve , refl
genMerge fused     _   = Fuse     , refl
genMerge conflated neq = ⊥-elim (neq refl)
  where open import Data.Empty using (⊥-elim)

--------------------------------------------------------------------------------
-- THE CALCULUS METATHEOREM — Honest Generation: honesty is closed under ▷, so a
-- term built from honest atoms can never produce a deceptive grade (HC-3).
-- Per-coordinate first, then lifted; the fate case is the F2-non-commutative one.
--------------------------------------------------------------------------------

fate-honest : ∀ a b → a ≢ falsified → b ≢ falsified → (a ▷f b) ≢ falsified
fate-honest present    b          anf bnf = bnf
fate-honest (atten d)  present    anf bnf = λ ()
fate-honest (atten d)  (atten e)  anf bnf = λ ()
fate-honest (atten d)  predicated anf bnf = λ ()
fate-honest (atten d)  dropped    anf bnf = λ ()
fate-honest (atten d)  falsified  anf bnf = λ _ → bnf refl
fate-honest predicated present    anf bnf = λ ()
fate-honest predicated (atten e)  anf bnf = λ ()
fate-honest predicated predicated anf bnf = λ ()
fate-honest predicated dropped    anf bnf = λ ()
fate-honest predicated falsified  anf bnf = λ _ → bnf refl
fate-honest dropped    b          anf bnf = λ ()
fate-honest falsified  b          anf bnf = λ _ → anf refl

bond-honest : ∀ a b → a ≢ misbound → b ≢ misbound → (a ▷b b) ≢ misbound
bond-honest intact   b        anf bnf = bnf
bond-honest withheld intact   anf bnf = λ ()
bond-honest withheld withheld anf bnf = λ ()
bond-honest withheld severed  anf bnf = λ ()
bond-honest withheld misbound anf bnf = λ _ → bnf refl
bond-honest severed  intact   anf bnf = λ ()
bond-honest severed  withheld anf bnf = λ ()
bond-honest severed  severed  anf bnf = λ ()
bond-honest severed  misbound anf bnf = λ _ → bnf refl
bond-honest misbound b        anf bnf = λ _ → anf refl

merge-honest : ∀ a b → a ≢ conflated → b ≢ conflated → (a ▷m b) ≢ conflated
merge-honest single    b         anf bnf = bnf
merge-honest fused     single    anf bnf = λ ()
merge-honest fused     fused     anf bnf = λ ()
merge-honest fused     conflated anf bnf = λ _ → bnf refl
merge-honest conflated b         anf bnf = λ _ → anf refl

-- A grade is HONEST when no coordinate hits its deceptive dual.
Honest : Grade → Set
Honest g = (fQuality g ≢ falsified) × (fBearer g ≢ falsified)
         × (fContext g ≢ falsified) × (fRecord g ≢ falsified)
         × (gBond g ≢ misbound) × (gMerge g ≢ conflated)

-- Honesty is CLOSED under the non-commutative composition ▷.
honest-closed-▷ : ∀ g h → Honest g → Honest h → Honest (g ▷ h)
honest-closed-▷ (mkGrade q₁ b₁ c₁ r₁ bo₁ m₁) (mkGrade q₂ b₂ c₂ r₂ bo₂ m₂)
  (hq₁ , hb₁ , hc₁ , hr₁ , hbo₁ , hm₁) (hq₂ , hb₂ , hc₂ , hr₂ , hbo₂ , hm₂) =
    fate-honest q₁ q₂ hq₁ hq₂ , fate-honest b₁ b₂ hb₁ hb₂
  , fate-honest c₁ c₂ hc₁ hc₂ , fate-honest r₁ r₂ hr₁ hr₂
  , bond-honest bo₁ bo₂ hbo₁ hbo₂ , merge-honest m₁ m₂ hm₁ hm₂

-- The writable effect atoms are honest (Generation.idr atoms, as grades).
ε-honest : Honest ε
ε-honest = (λ ()) , (λ ()) , (λ ()) , (λ ()) , (λ ()) , (λ ())

atten-atom-honest : ∀ δ → Honest (atten-atom δ)
atten-atom-honest δ = (λ ()) , (λ ()) , (λ ()) , (λ ()) , (λ ()) , (λ ())

drop-atom-honest : Honest drop-atom
drop-atom-honest = (λ ()) , (λ ()) , (λ ()) , (λ ()) , (λ ()) , (λ ())

sever-atom-honest : Honest sever-atom
sever-atom-honest = (λ ()) , (λ ()) , (λ ()) , (λ ()) , (λ ()) , (λ ())

predicate-atom-honest : Honest predicate-atom
predicate-atom-honest = (λ ()) , (λ ()) , (λ ()) , (λ ()) , (λ ()) , (λ ())

-- ε is honest (Veridicality.idr epsilonHonest), and stays honest under any honest
-- effect — the deceptive grades are UNREACHABLE from honest terms (HC-3, dynamic).
preserve-stays-honest : ∀ g → Honest g → Honest (g ▷ ε)
preserve-stays-honest g hg = honest-closed-▷ g ε hg ε-honest

attenuate-stays-honest : ∀ g δ → Honest g → Honest (g ▷ atten-atom δ)
attenuate-stays-honest g δ hg = honest-closed-▷ g (atten-atom δ) hg (atten-atom-honest δ)

detach-stays-honest : ∀ g → Honest g → Honest (g ▷ sever-atom)
detach-stays-honest g hg = honest-closed-▷ g sever-atom hg sever-atom-honest

collapse-stays-honest : ∀ g → Honest g → Honest (g ▷ predicate-atom)
collapse-stays-honest g hg = honest-closed-▷ g predicate-atom hg predicate-atom-honest
